# Пользователи
## Создать нового пользователя

POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatarPath": "torrance.png",
  "name": "Jack",
  "type": "standart",
  "password": "shining"
}

###
