# Пользователи
## Создать нового пользователя

POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatarUrl": "torrance.png",
  "name": "Jack",
  "type": "standart",
  "password": "shining"
}

###

## Авторизовать пользователя

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Получить информацию о текущем пользователе

GET http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

###

## Завершить текущий сеанс пользователя

POST http://localhost:3000/users/logout HTTP/1.1
Content-Type: application/json

###
