# Предложения
## Получить список предложений
GET http://localhost:3000/offers?limit=10 HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение
POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Тест Тест Тест Тест",
  "description": "Сдаем посуточно большую 2к квартиру рядом с озером Кабан, с прямым выходом со двора к туристическим прогулочным улицам Каюма Насыри и Марджани, туристам, гостям города или командировочным. В пешей доступности самые интересные достопримечательности города. Рядом музеи, театры, кафе, рестораны.",
  "postDate": "2023-11-03T20:13:04.703Z",
  "city": "Cologne",
  "previewImage": "Apartment-with-Jacuzzi.jpg",
  "images": [
    "Triple-bed.png",
    "jacuzzi.jpg",
    "spacious-hall.jpg",
    "View-from-the-window.png",
    "quiet-entrance.png",
    "kitchen-with-refrigerator.jpg"
  ],
  "isPremium": true,
  "type": "room",
  "bedrooms": 3,
  "maxAdults": 3,
  "price": 31703,
  "goods": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Baby seat"
  ],
  "hostId": "654948f643d8be512e7617ce",
  "location": {
    "longitude": 30.977954,
    "latitude": 52.535441
  }
}

###

## Получить список премиальных предложений для города.
GET http://localhost:3000/offers/premium/hamburg HTTP/1.1
Content-Type: application/json

###

## Получить детальную информацию о предложении.
GET http://localhost:3000/offers/654948f643d8be512e7617d5 HTTP/1.1
Content-Type: application/json

###

## Редактировать предложение
PATCH  http://localhost:3000/offers/65511b334f34179d36288016 HTTP/1.1
Content-Type: application/json

{
  "title": "Тест1",
  "description": "1Сдаем посуточно большую 2к квартиру рядом с озером Кабан, с прямым выходом со двора к туристическим прогулочным улицам Каюма Насыри и Марджани, туристам, гостям города или командировочным. В пешей доступности самые интересные достопримечательности города. Рядом музеи, театры, кафе, рестораны.",
  "isPremium": false
}

###

## Удалить предложение
DELETE  http://localhost:3000/offers/65511b334f34179d36288016 HTTP/1.1
Content-Type: application/json

###

## Список комментариев к объявлению
GET http://localhost:3000/offers/654948f643d8be512e7617d5/comments HTTP/1.1

###
